javascript:(async()=>{const cfg={maxDepth:5,maxFiles:350,openLimit:50};const overlayId='__param_scanner_overlay_v3';if(document.getElementById(overlayId)){document.getElementById(overlayId).remove();return;}const $=(t,attrs={})=>{const e=document.createElement(t);for(const k in attrs)if(k==='html')e.innerHTML=attrs[k];else e.setAttribute(k,attrs[k]);return e};const overlay=$('div',{id:overlayId,style:'position:fixed;left:12px;top:12px;right:12px;bottom:12px;z-index:2147483647;background:#fff;border:2px solid #222;padding:12px;overflow:auto;font-family:Inter,Arial,Helvetica,sans-serif;font-size:13px;color:#111;box-shadow:0 8px 40px rgba(0,0,0,.45)'});const header=$('div',{html:'<strong>Deep Param Scanner</strong> — scanning...'});const closeBtn=$('button',{html:'Close'});closeBtn.style.float='right';closeBtn.onclick=()=>overlay.remove();header.appendChild(closeBtn);overlay.appendChild(header);const info=$('div',{style:'margin:8px 0 12px 0;'});overlay.appendChild(info);const resultsEl=$('div',{});overlay.appendChild(resultsEl);document.body.appendChild(overlay);const visited=new Set();let fileCount=0;const results={};const enqueue=[];const logProgress=()=>{info.innerText=`Scanned: ${fileCount} — queued: ${enqueue.length}`};const resolve=(u,base)=>{try{return new URL(u,base).href}catch(e){return null}};const extractQueryParamsFromUrlString=s=>{try{const u=new URL(s,location.href);return Array.from(new Set(Array.from(u.searchParams.keys())))}catch(e){const qIdx=s.indexOf('?');if(qIdx===-1)return[];const qs=s.slice(qIdx+1).split(/[#'"\s]/)[0];return Array.from(new Set(qs.split('&').map(p=>p.split('=')[0]).filter(Boolean)))}};const extractUrlsFromText=t=>{const urls=new Set();const litRe=/['"`]((?:\\.|[^'"`])*)['"`]/g;let m;while(m=litRe.exec(t)){const inner=m[1];(inner.match(/https?:\/\/[^\s'"]+/g)||[]).forEach(x=>urls.add(x));const ext=(inner.match(/([A-Za-z0-9_\-]+)=/g)||[]).map(x=>x.replace(/=$/,''));}const genericUrlRe=/\b(?:https?:\/\/|\/)[^\s'"]+\.(?:js|html|htm)(?:\?[^\s'"]*)?/g;while(m=genericUrlRe.exec(t))urls.add(m[0]);return Array.from(urls)};const extractParamsDeep=text=>{const out=new Set();if(!text||!text.length) return out; // 1) explicit URLs in text
(text.match(/https?:\/\/[^\s'"]+/g)||[]).forEach(u=>extractQueryParamsFromUrlString(u).forEach(p=>out.add(p))); // 2) string literals: look for param= inside them
const litRe=/['"`]((?:\\.|[^'"`])*)['"`]/g;let m;while(m=litRe.exec(text)){const s=m[1];const paramRe=/([A-Za-z0-9_%\-]+)=/g;let mm;while(mm=paramRe.exec(s)){out.add(mm[1])}} // 3) URLSearchParams('a=1&b=2') content
const uspRe=/URLSearchParams\s*\(\s*['"`]([^'"]+)['"`]\s*\)/g;while(m=uspRe.exec(text)){const body=m[1];body.split('&').forEach(p=>{const k=p.split('=')[0];if(k)out.add(k)})} // 4) .get('param'), .set('param',...), .append('param',...), searchParams.get('param')
const methodRe=/(?:searchParams|URLSearchParams)?\.(?:get|set|append)\s*\(\s*['"`]([^'"]+)['"`]/g;while(m=methodRe.exec(text)){out.add(m[1])} // 5) new URL(...).searchParams.get('x')
const searchParamsGetRe=/searchParams\.get\s*\(\s*['"`]([^'"]+)['"`]\s*\)/g;while(m=searchParamsGetRe.exec(text)){out.add(m[1])} // 6) common helper getParameterByName('x')
const helperRe=/getParameterByName\s*\(\s*['"`]([^'"]+)['"`]\s*\)/g;while(m=helperRe.exec(text)){out.add(m[1])} // 7) regex for key= in the whole file (catch other constructions)
const anyPairRe=/[?&\s]([A-Za-z0-9_%\-]+)=/g;while(m=anyPairRe.exec(text)){out.add(m[1])} return out};const extractFunctionParams=text=>{const names=new Set();const r1=/function\s*[^(]*\(([^)]*)\)/g,r2=/\(([^\)]*)\)\s*=>/g,r3=/([A-Za-z0-9_$]+)\s*=>/g;let m;while(m=r1.exec(text)){m[1].split(',').map(x=>x.trim()).filter(Boolean).forEach(p=>names.add(p))}while(m=r2.exec(text)){m[1].split(',').map(x=>x.trim()).filter(Boolean).forEach(p=>names.add(p))}while(m=r3.exec(text)){names.add(m[1])}return Array.from(names)};async function fetchAndScan(url,depth){if(fileCount>=cfg.maxFiles||depth>cfg.maxDepth||!url||visited.has(url))return;visited.add(url);fileCount++;logProgress();results[url]={links:[],params:new Set(),formParams:new Set(),funcParams:[]};try{const res=await fetch(url,{credentials:'include'});if(!res.ok){results[url].error=`HTTP ${res.status}`;return}const ctype=res.headers.get('content-type')||'';const text=await res.text(); // parse HTML vs JS/text
if(ctype.includes('html')||text.trim().startsWith('<')){try{const doc=new DOMParser().parseFromString(text,'text/html'); // links
Array.from(doc.querySelectorAll('script[src],link[href],a[href],iframe[src],img[src]')).forEach(n=>{const u=n.getAttribute('src')||n.getAttribute('href');const r=resolve(u,url);if(r)results[url].links.push(r)}); // forms
Array.from(doc.querySelectorAll('form')).forEach(f=>{const a=f.getAttribute('action'); if(a){extractQueryParamsFromUrlString(a).forEach(p=>results[url].formParams.add(p))}Array.from(f.querySelectorAll('[name]')).forEach(el=>{if(el.name)results[url].formParams.add(el.name)})}); // deep param extraction from HTML text
extractParamsDeep(text).forEach(p=>results[url].params.add(p)); // enqueue links
for(const l of results[url].links){const abs=resolve(l,url);if(abs && !visited.has(abs))enqueue.push({url:abs,depth:depth+1});} }catch(e){results[url].error=`HTML parse error: ${e.message}`} } else { // treat as JS or other text
// discovered links from string literals or import-like patterns
(extractUrlsFromText(text)||[]).forEach(l=>{const r=resolve(l,url); if(r) results[url].links.push(r)}); // deep param extraction
extractParamsDeep(text).forEach(p=>results[url].params.add(p)); // function params
extractFunctionParams(text).forEach(p=>results[url].funcParams.push(p)); // enqueue
for(const l of results[url].links){const abs=resolve(l,url); if(abs && !visited.has(abs)) enqueue.push({url:abs,depth:depth+1});} } }catch(err){results[url].error=err.message} } // start from current document
(async()=>{const start=location.href;results[start]={links:[],params:new Set(),formParams:new Set(),funcParams:[]}; // collect links and page form names
try{Array.from(document.querySelectorAll('script,link,a,iframe,img')).forEach(n=>{const u=n.src||n.href;const r=resolve(u,start); if(r) results[start].links.push(r)});Array.from(document.querySelectorAll('form')).forEach(f=>{const a=f.action; if(a) extractQueryParamsFromUrlString(a).forEach(p=>results[start].formParams.add(p)); Array.from(f.querySelectorAll('[name]')).forEach(e=>{ if(e.name) results[start].formParams.add(e.name) })}); // inline scripts scan
Array.from(document.querySelectorAll('script')).forEach(s=>{ if(!s.src){const t=s.textContent||''; extractParamsDeep(t).forEach(p=>results[start].params.add(p)); extractFunctionParams(t).forEach(p=>results[start].funcParams.push(p)); extractUrlsFromText(t).forEach(u=>{const r=resolve(u,start); if(r) results[start].links.push(r)})}}); // queue initial links
results[start].links.forEach(l=>{const abs=resolve(l,start); if(abs && !visited.has(abs)) enqueue.push({url:abs,depth:1})});visited.add(start);fileCount++;logProgress();}catch(e){console.error('start parse',e)} // worker loop
while(enqueue.length && fileCount<cfg.maxFiles){const job=enqueue.shift(); if(!job) break; if(job.depth>cfg.maxDepth) continue; if(visited.has(job.url)) continue; await fetchAndScan(job.url,job.depth);} // finalize sets -> arrays
for(const u in results){results[u].params=[...results[u].params];results[u].formParams=[...results[u].formParams];results[u].links=[...new Set(results[u].links)];results[u].funcParams=[...new Set(results[u].funcParams)];} // render
resultsEl.innerHTML='';const summary=$('div',{html:`<strong>Scanned:</strong> ${fileCount} &nbsp;|&nbsp; Entries: ${Object.keys(results).length}`});overlay.insertBefore(summary,resultsEl);for(const u of Object.keys(results)){const d=results[u];const card=$('div',{style:'border:1px solid #ddd;padding:8px;margin:8px 0;border-radius:6px;'});card.appendChild($('div',{html:`<strong>${u}</strong>`}));if(d.error)card.appendChild($('div',{html:`<em style="color:#900">Error: ${d.error}</em>`}));if(d.params.length)card.appendChild($('div',{html:`<u>Params (from strings/APIs)</u>: ${d.params.join(', ')}`}));if(d.formParams.length)card.appendChild($('div',{html:`<u>Form/input names</u>: ${d.formParams.join(', ')}`}));if(d.funcParams.length)card.appendChild($('div',{html:`<u>JS function params</u>: ${d.funcParams.slice(0,60).join(', ')}${d.funcParams.length>60?' ...':''}`}));if(d.links.length){const ldiv=$('div',{});ldiv.appendChild($('div',{html:`<u>Links (${d.links.length})</u>`}));const ul=$('ul',{});d.links.slice(0,200).forEach(link=>{const li=$('li',{});const a=$('a',{html:link});a.href=link;a.target='_blank';li.appendChild(a);ul.appendChild(li)});ldiv.appendChild(ul);card.appendChild(ldiv);}resultsEl.appendChild(card);}const copyBtn=$('button',{html:'Copy JSON'});copyBtn.onclick=()=>navigator.clipboard.writeText(JSON.stringify(results,null,2)).then(()=>alert('Copied')).catch(()=>alert('Copy failed'));overlay.appendChild(copyBtn);const openBtn=$('button',{html:'Open di_
